
---
- name: Install common packages across different Linux distros
  hosts: localhost
  become: true
  vars:
    common_packages:
      - git
      - curl
      - htop
      # for Tmux-sessionizer
      - tmux
      - fzf
      # Better CLI
      - eza
      - fastfetch


  tasks:
    - name: Initialize os_packages
      set_fact:
        os_packages: "{{ common_packages }}"

    - name: Set package list for Ubuntu/Debian
      set_fact:
        os_packages: "{{ common_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Set package list for openSUSE
      set_fact:
        os_packages: "{{ common_packages }}"
      when: ansible_distribution == 'openSUSE'

    - name: Set package list for macOS (Homebrew names may differ)
      set_fact:
        os_packages: "{{ common_packages }}"
      when: ansible_os_family == 'Darwin'

    - name: Ensure Homebrew is installed (macOS only)
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ os_packages }}"
      when: ansible_os_family == 'Darwin'

    - name: Show package list to install
      debug:
        var: os_packages
    - name: Install packages on Ubuntu/Debian
      apt:
        name: "{{ os_packages }}"
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    # SUSE/openSUSE (sudo required)
    - name: Install packages on SUSE/openSUSE
      become: true
      zypper:
        name: "{{ os_packages }}"
        state: present
        update_cache: true
      when: ansible_facts.os_family == 'Suse'
