mapped_packages:
  - netcat
  - telnet
  - golang
  - docker
  - fd
  - dnsutils
  - iproute

package_map:
  netcat:
    Alpine: netcat-openbsd
    Archlinux: netcat
    Darwin: netcat
    Debian: netcat-openbsd
    RedHat: nmap-ncat
    Suse: netcat-openbsd

  telnet:
    Alpine: busybox-extras
    Archlinux: inetutils
    Darwin: inetutils
    Debian: telnet
    RedHat: telnet
    Suse: telnet

  golang:
    Alpine: go
    Archlinux: go
    Darwin: go
    Debian: golang
    RedHat: golang
    Suse: go

  docker:
    Alpine: docker
    Archlinux: docker
    Debian: docker.io
    RedHat: docker
    Suse: docker
    # Darwin: docker

  fd:
    Alpine: fd-find
    Archlinux: fd
    Darwin: fd
    Debian: fd-find
    RedHat: fd-find
    Suse: fd

  dnsutils:
    Debian: dnsutils
    RedHat: bind-utils
    Suse: bind-utils
    Archlinux: bind
    Alpine: bind-tools
    Darwin: bind

  iproute:
    Debian: iproute2
    RedHat: iproute
    Suse: iproute2
    Archlinux: iproute2
    Alpine: iproute2
    Darwin: iproute2mac 
