mapped_packages:
  - netcat
  - telnet
  - golang
  - docker
  - fd
  - dnsutils
  - iproute
  - snmp
  - python3-pip
  - pipx
  - yarn
  - iperf3

package_map:
  netcat:
    Alpine: netcat-openbsd
    Archlinux: netcat
    Darwin: netcat
    Debian: netcat-openbsd
    RedHat: nmap-ncat
    Suse: netcat-openbsd

  telnet:
    Alpine: busybox-extras
    Archlinux: inetutils
    Darwin: inetutils
    Debian: telnet
    RedHat: telnet
    Suse: telnet

  golang:
    Alpine: go
    Archlinux: go
    Darwin: go
    Debian: golang
    RedHat: golang
    Suse: go

  docker:
    Alpine: docker
    Archlinux: docker
    Debian: docker.io
    RedHat: docker
    Suse: docker
    # Darwin: docker

  fd:
    Alpine: fd-find
    Archlinux: fd
    Darwin: fd
    Debian: fd-find
    RedHat: fd-find
    Suse: fd

  dnsutils:
    Debian: dnsutils
    RedHat: bind-utils
    Suse: bind-utils
    Archlinux: bind
    Alpine: bind-tools
    Darwin: bind

  iproute:
    Debian: iproute2
    RedHat: iproute
    Suse: iproute2
    Archlinux: iproute2
    Alpine: iproute2
    Darwin: iproute2mac 

  snmp:
    Debian: snmp
    Archlinux: net-snmp
    RedHat: [net-snmp, net-snmp-utils]
    Suse: net-snmp
    Alpine: net-snmp
    Darwin: net-snmp

  python3-pip:
    Debian: python3-pip
    Archlinux: python-pip
    RedHat: python3-pip
    Suse: python3-pip
    Alpine: py3-pip
    Darwin: python

  pipx:
    Debian: pipx
    Archlinux: python-pipx
    RedHat: pipx
    Suse: pipx   
    Alpine: pipx 
    Darwin: pipx

  yarn:
    Debian: yarn
    Archlinux: yarn
    RedHat: yarnpkg
    Suse: yarn
    Alpine: yarn
    Darwin: yarn

  iperf3:
    Debian: iperf3
    Archlinux: iperf3
    RedHat: iperf3
    Suse: iperf   # if this still fails, change to iperf
    Alpine: iperf3
    Darwin: iperf3

