"$schema" = 'https://starship.rs/config-schema.json'

# format ="""
#  $os\
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_status\
# $aws\
# $buf\
# $c\
# $conda\
# $dart\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $haxe\
# $hg_branch\
# $java\
# $julia\
# $lua\
# $meson\
# $nim\
# $nodejs\
# $pijul_channel\
# $python\
# $rlang\
# $ruby\
# $rust\
# $scala\
# $package\
# $docker_context\
# $line_break$character\
# """
format ="""
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$aws\
$buf\
$c\
$conda\
$dart\
$elixir\
$elm\
$golang\
$haskell\
$haxe\
$hg_branch\
$java\
$julia\
$lua\
$meson\
$nim\
$nodejs\
$pijul_channel\
$python\
$rlang\
$ruby\
$rust\
$scala\
$package\
$docker_context\
$character\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "fg:color_green"

[username]
show_always = true
style_user = "color_green"
style_root = "color_green"
format = '[$user]($style) '

[hostname]
ssh_symbol = " "
style = "color_green"
format = ' at [$ssh_symbol$hostname]($style) '

[directory]
style = "color_blue"
format = "[$path]($style) "
read_only = " 󰌾"

[git_branch]
symbol = ""
style = "color_purple"
format = '[$symbol $branch ]($style)'

[git_status]
style = "color_orange"
format = '[($all_status$ahead_behind )]($style)'

#Nerd Fonts
[aws]
symbol = " "
style = "color_yellow"
format = '[$symbol aws $version ]($style)'

[c]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol c $version ]($style)'

[conda]
symbol = " "
style = "color_yellow"

[dart]
symbol = " "
style = "color_yellow"

[docker_context]
symbol = " "
style = "color_yellow"
format = '[$symbol( $context) ]($style)'

[elixir]
symbol = " "
style = "color_yellow"

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "
style = "color_yellow"

[guix_shell]
symbol = " "

[haskell]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Haskell $version ]($style)'

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Java $version ]($style)'

[julia]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Julia $version ]($style)'

[lua]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Lua $version ]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Nodejs $version ]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Python $version ]($style)'

[rlang]
symbol = "󰟔"
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol R $version ]($style)'

[ruby]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Ruby $version ]($style)'

[rust]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Rust $version ]($style)'

[scala]
symbol = ""
style = "color_yellow"
version_format = "v${major}.${minor}"
format = '[$symbol Scala $version ]($style)'

[character]
disabled = false
# success_symbol = '[](bold fg:color_green)'
# error_symbol = '[](bold fg:color_red)'
success_symbol = '[❯](bold fg:color_aqua)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[line_break]
disabled = false


[directory.substitutions]
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"
"Music" = "󰝚 Music"
"Pictures" = " Pictures"
"Developer" = "󰲋 Developer"
"Desktop" = " Desktop"
