
---
- name: Install common packages across different Linux distros
  hosts: all
  become: true
  vars:
    common_packages:
      - git
      - curl
      - htop

  tasks:
    - name: Set package list for Ubuntu/Debian
      set_fact:
        os_packages: "{{ common_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Set package list for openSUSE
      set_fact:
        os_packages: "{{ common_packages }}"
      when: ansible_distribution == 'openSUSE'

    - name: Set package list for macOS (Homebrew names may differ)
      set_fact:
        os_packages: "{{ common_packages }}"
      when: ansible_os_family == 'Darwin'

    - name: Ensure Homebrew is installed (macOS only)
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ os_packages }}"
      when: ansible_os_family == 'Darwin'

    - name: Install packages on Ubuntu/Debian
      apt:
        name: "{{ os_packages }}"
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install packages on openSUSE
      zypper:
        name: "{{ os_packages }}"
        state: present
      when: ansible_distribution == 'openSUSE'
